services:
  server:
    build: ./file-server
    image: jaycebordelon/optifile-server:latest
    container_name: optifile-server
    ports:
      - '8080:8080'
    volumes:
      - optifile-data:/app/uploads
    environment:
      - PORT=8080
      - UPLOAD_PATH=./uploads
      - APP_ENV=production

  client:
    build: ./client
    image: jaycebordelon/optifile-client:latest
    container_name: optifile-client
    ports:
      - '3000:3000'

volumes:
  optifile-data:
    name: optifile-data
