services:
  server:
    build: .
    image: jaycebordelon/optifile-server:latest
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - UPLOAD_PATH=./uploads
      - APP_ENV=production
